name: Test build of react-util

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout sources 🔰
      uses: actions/checkout@v4

    - name: Setup Node.js 20 👷🏻
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Cache Node.js modules 💾
      uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6
      with:
        path: ~/.npm
        key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.OS }}-node-
          ${{ runner.OS }}-

    - name: Install dependencies ⏬
      run: npm ci

    - name: Lint code 💄
      run: npm run lint

    - name: Test code ✅
      run: npm run test-ci

    - name: Build artifacts 🏗️
      run: npm run build

    - name: Publish to coveralls ⭐
      # coverage/lcov.info was generated in the previous npm run build step
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
